name: distributed-process-p2p
version: 0.1.5.0
synopsis: Peer-to-peer node discovery for Cloud Haskell
description: Bootstraps a peer-to-peer connection network from a set of known hosts.
category: Network
author: Alexander Bondarenko
maintainer: aenor.realm@gmail.com
copyright: Alexander Bondarenko
license: BSD3
homepage: https://bitbucket.org/dpwiz/distributed-process-p2p/
git: git@bitbucket.org:dpwiz/distributed-process-p2p.git

extra-source-files:
- CHANGELOG

dependencies:
- base ==4.*
- mtl >= 2.1
- distributed-process >=0.5

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Control.Distributed.Backend.P2P
  dependencies:
  - bytestring >=0.9
  - containers >=0.4
  - binary >=0.5
  - network >=2.3
  - network-transport >=0.4
  - network-transport-tcp >=0.6

executables:
  jollycloud:
    main: JollyCloud.hs
    source-dirs: tests/
    ghc-options: -threaded
    dependencies:
    - distributed-process-p2p
    when:
    - condition: flag(build-example)
      buildable: true

flags:
  build-example:
    description: Build "jollycloud" example which can serve as a p2p broker node.
    manual: false
    default: false
